spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medtest
    driverClassName: org.h2.Driver
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  sql:
    init:
      mode: never
jwt:
  secret: helloworld
  jwtExpirationMs: 86400000